### ISSUE TITLE
error=nfpm failed: rpmbuild not present in $PATH

### ISSUE THREAD

**Issue by marcofranssen** [goreleaser/nfpm#61] opened 2019-07-22 10:47 UTC
Is there any manual step to do on windows to get goreleaser / nfpm working on Windows?

**Comment by caarlos0** [comment] 2019-07-22 12:33
haven't tested on windows... maybe we need to look for `rpmbuild.exe` instead?

do rpmbuild work on windows?

**Comment by caarlos0** [comment] 2019-08-25 14:47
closing as its not a bug

**Closed by caarlos0** 2019-08-25 14:47 UTC
Labels: question

**Comment by marcofranssen** [comment] 2019-09-23 09:23
The problem is that rpmbuild is not available it fails the full goreleaser process. IMHO it would be better to succeed the remainder and skip the rpm build with a message informing the user. Now I always comment the rpm parts on windows to test the remainder.

**Comment by caarlos0** [comment] 2019-09-23 12:13
only on windows, when using goreleaser, correct?

**Comment by SamuelMarks** [comment] 2019-09-24 00:44
There are alternative implementations of `rpmbuild` that are cross-platform, e.g.: https://ctron.github.io/rpm-builder/

**Comment by marcofranssen** [comment] 2019-09-24 11:39
@caarlos0 yes correct, but might also occur on linux if the tools are not installed for example ;) IMHO it should not block the other artifact types from being released.

**Comment by caarlos0** [comment] 2019-09-24 17:53
I think it actually should.

The idea is to have the release behave always in the same way, if the user expects to generate rpm files, and it fails for whatever reason, the entire process should fail.

That being said, this is working as expected.

**Comment by jarondl** [comment] 2019-10-04 00:30
This should be fixed soon by using google/rpmpack with the work done by @djgilcrease

**Comment by Prnyself** [comment] 2020-01-08 08:49
> This should be fixed soon by using google/rpmpack with the work done by @djgilcrease

git pull new version and then make build did save my day

**Comment by caarlos0** [comment] 2020-11-17 00:49
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
