### ISSUE TITLE
Signed RPMs failed to install via yum/dnf on RHEL7/CentOS7

### ISSUE THREAD

**Issue by zbindenren** [goreleaser/nfpm#265] opened 2020-12-17 10:02 UTC
**Describe the bug**

We are using the new RPM sign feature, and everything seems to work fine until installation.

Installation with yum:

```
Total download size: 4.5 M
Installed size: 12 M
Background downloading packages, then exiting:
error: /var/cache/yum/x86_64/7Server/linux-rpm-releases-local/packages/lslbgen-0.0.3.x86_64.rpm: Verify signature: BAD PARAMETERS (1002 0x31ecea0 72 (nil) 0x2bde520)
Problem opening package lslbgen-0.0.3.x86_64.rpm
lslbgen-0.0.3.x86_64.rpm    
```

We get the error `Verify signature: BAD PARAMETERS (1002 0x31ecea0 72 (nil) 0x2bde520)`

If we inspect the package with `rpm` everything seems ok:

```
rpm -K /var/cache/yum/x86_64/7Server/linux-rpm-releases-local/packages/lslbgen-0.0.3.x86_64.rpm -v
/var/cache/yum/x86_64/7Server/linux-rpm-releases-local/packages/lslbgen-0.0.3.x86_64.rpm:
    V4 DSA/SHA256 Signature, key ID 499702cb: OK
```

We also tried with a RSA key and we get the same error.

With RHEL8 it is possible to install the package via yum/dnf without a problem.
                        
**To Reproduce**

Build a signed RPM. Install the resulting package.

**Expected behavior**
Installation should be possible.

**Environment (please complete the following information):**
```
uname -a
Linux 3.10.0-1160.2.2.el7.x86_64 goreleaser/goreleaser#1 SMP Sat Oct 17 05:06:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
Add any other context about the problem here. Full output log with debug on
is probably a helpful thing to add here.

**Comment by caarlos0** [comment] 2020-12-17 17:22
cc/ @erikgeiser since you worked on this

**Comment by erikgeiser** [comment] 2020-12-17 18:36
So `nfpm` receives the data which needs to be signed from https://github.com/google/rpmpack and sends an armored detached signature created with `/x/crypto/openpgp` back to `rpmpack` which then embeds it in the `rpm`.

I can't reproduce the behaviour with freshly generated keys. For me it just works on `centos7` and `centos8`. However, I used RSA keys and we also just test with RSA keys. The output of your last message shows that the package signed with `rpm` was also signed with RSA keys and your broken packages was signed with DSA keys. I also found this serverfault thread that mentions that `rpm` can be picky with different key algorithms and key sizes https://serverfault.com/questions/624888/bad-signatures-or-nokey-errors-on-rpms-i-just-signed. So I guess the problem is your key.

Could you please test it with an RSA key? I would also generally recommend not to use DSA keys anymore (read https://buttondown.email/cryptography-dispatches/archive/557475c5-9781-47e0-a640-5734bc849bc7 for more information).

If the key algorithm is indeed the problem, we should document it an check the key algorithm in `internal/sign`.

**Comment by zbindenren** [comment] 2020-12-18 06:27
@erikgeiser thanks for the quick response. Unfortunately it does not work with RSA Keys also:

If I try to install the generated package with yum I get again `BAD PARAMETERS` error:

```
yum install package --downloadonly 
...
Total download size: 566 k
Background downloading packages, then exiting:
No Presto metadata available for linux-rpm-staging-local
error: /var/cache/yum/x86_64/7Server/linux-rpm-staging-local/packages/package-0.0.2-rc14.x86_64.rpm: Verify signature: BAD PARAMETERS (1002 0x368e020 287 (nil) 0x36acea0)                                                                                                                                           ]  0.0 B/s |    0 B  --:--:-- ETA 
Problem opening package package-0.0.2-rc14.x86_64.rpm
package-0.0.2-rc14.x86_64.rpm                                                                                                                                                                                                                                                                                                   | 566 kB  00:00:00     
exiting because "Download Only" specified
```

If I check the package with the `rpm` utility it seems to be ok:
```
rpm -Kv /var/cache/yum/x86_64/7Server/linux-rpm-staging-local/packages/package-0.0.2-rc14.x86_64.rpm
/var/cache/yum/x86_64/7Server/linux-rpm-staging-local/packages/package-0.0.2-rc14.x86_64.rpm:
    V4 RSA/SHA256 Signature, key ID 4593ca3c: OK
```

But if you compare the output of a rpm signed by the rpm utility:

```
rpm -Kv create-go-app-0.7.3-1.x86_64.rpm 
create-go-app-0.7.3-1.x86_64.rpm:
    Header V4 RSA/SHA1 Signature, key ID f8427f69: NOKEY
    Header SHA1 digest: OK (f836250b71747d741d673ce21bf03ccf50a8be64)
    V4 RSA/SHA1 Signature, key ID f8427f69: NOKEY
    MD5 digest: OK (e6f2d85b628144c9f49ba427004d5697)
```

you see that there are more entries (Header, MD5 etc...). I am not sure if this is the problem.

Maybe you can reproduce it with the uploaded [key-material.tar.gz](https://github.com/goreleaser/nfpm/files/5714014/key-material.tar.gz).

**Comment by erikgeiser** [comment] 2020-12-18 17:16
I tried it with your key and it works in the `centos6`, `centos7` and `centos8` Docker images. What's interesting is that while `centos6` and `centos7` show the following...

```sh
$ rpm -Kv foo-1.0.0.x86_64.rpm
foo-1.0.0.x86_64.rpm:
    V4 RSA/SHA256 Signature, key ID 4593ca3c: OK
```
... `centos8` shows this with exactly the same package file:

```sh
$ rpm -Kv foo-1.0.0.x86_64.rpm
foo-1.0.0.x86_64.rpm:
    Header SHA256 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA256 Signature, key ID 4593ca3c: OK
``` 

However, in all cases it can be verified and installed just fine (both with `rpm -i` and `yum install`). There also seem to be multiple `rpm` tags for signatures and `rpmpack` only sets one, so this may be the reason for this discrepancy. I found some threads where people say that the way keys are discovered in an `rpm` package changed between the versions. But even if not all digests were discovered, the signature `nfpm` provides should still work.

So now we still don't know why it won't install on your machine.

**Comment by zbindenren** [comment] 2020-12-21 07:08
I tried with Centos and got the same error. I used the following Dockerfile (I replaced our internal domain to `example.com`):

```
FROM centos:7

COPY releaser.repo /etc/yum.repos.d/releaser.repo
COPY key.gpg /tmp/key.gpg

RUN rpm --import /tmp/key.gpg
ENV http_proxy=http://proxy.example.com:3128 \
    https_proxy=http://proxy.example.com:3128 \
    no_proxy=localhost,.exaple.com

RUN yum clean all
```

With the following yum repository `releaser.repo`:
```
[releaser]
name=Releaser RPM Packages
baseurl=https://artifactory.example.com/artifactory/rhel7/
enabled=1
gpgcheck=1
gpgkey=file:///tmp/key.gpg
sslverify=0
```

When I install a package I get the same error as on RHEL7:

```
Downloading packages:
error: /var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm: Verify signature: BAD PARAMETERS (1002 0x12e8ed0 72 (nil) 0x17473e0)
Problem opening package lslbgen-0.0.3-rc10.x86_64.rpm
lslbgen-0.0.3-rc10.x86_64.rpm                                                                                                                                                                                                                                                                                                   | 4.5 MB  00:00:00     
error: /var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm: Verify signature: BAD PARAMETERS (1002 0x136dac0 72 (nil) 0x19dd8b0)
```

RPM binary thinks everything is ok:

```
rpm -K /var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm
/var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm: (md5) pgp OK
```

And when I try to install the downloaded RPM, it works:

```
yum install /var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm
Loaded plugins: fastestmirror, ovl
Examining /var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm: lslbgen-0.0.3~rc10-1.x86_64
Marking /var/cache/yum/x86_64/7/releaser/packages/lslbgen-0.0.3-rc10.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package lslbgen.x86_64 0:0.0.3~rc10-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================================================================================================================================================================================================================================
 Package                                                                       Arch                                                                         Version                                                                             Repository                                                                                        Size
=======================================================================================================================================================================================================================================================================================================================================================
Installing:
 lslbgen                                                                       x86_64                                                                       0.0.3~rc10-1                                                                        /lslbgen-0.0.3-rc10.x86_64                                                                        12 M

Transaction Summary
=======================================================================================================================================================================================================================================================================================================================================================
Install  1 Package

Total size: 12 M
Installed size: 12 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Verifying  : lslbgen-0.0.3~rc10-1.x86_64                                                                                                                                                                                                                                                                                                         1/1 

Installed:
  lslbgen.x86_64 0:0.0.3~rc10-1                                                                                                                                                                                                                                                                                                                        

Complete!
```

**Comment by erikgeiser** [comment] 2020-12-21 20:14
@djgilcrease you said you were working on a fix? Do you already have an idea what might be the cause?

My best would be either a bug in rpm or a policy difference between downloads and local installs where different digest/signature tags in the rpm are checked/required. No real evidence to support that guess though.

**Comment by djgilcrease** [comment] 2020-12-21 21:16
> @djgilcrease you said you were working on a fix? Do you already have an idea what might be the cause?
> 
> My best would be either a bug in rpm or a policy difference between downloads and local installs where different digest/signature tags in the rpm are checked/required. No real evidence to support that guess though. But if this is indeed the case it would probably have to be fixed in rpmpack.

I think the issue could be fixed in nfpm. Changing the `PGPSigner` to use MD5 _fixes_ the issue, which just tells me we are not setting a field properly to set the Algo used to verify the pgp. Will keep digging to see if I can find the field and value that needs to be set.

```go
func PGPSigner(keyFile, passphrase string) func([]byte) ([]byte, error) {
	return func(data []byte) ([]byte, error) {
		key, err := readSigningKey(keyFile, passphrase)
		if err != nil {
			return nil, &nfpm.ErrSigningFailure{Err: err}
		}

		var signature bytes.Buffer

		err = openpgp.DetachSign(&signature, key, bytes.NewReader(data), &packet.Config{
			DefaultHash: crypto.MD5,
		})
		if err != nil {
			return nil, &nfpm.ErrSigningFailure{Err: err}
		}

		return signature.Bytes(), nil
	}
}
```

**Comment by djgilcrease** [comment] 2020-12-21 22:06
So when I use the code as is I get the following output
```bash
[root@e205f954c374 /]# rpmkeys -Kv /tmp/pkg/signed_rpm.rpm
/tmp/pkg/signed_rpm.rpm:
    V4 RSA/SHA256 Signature, key ID 15bd80b3: OK
[root@e205f954c374 /]# rpmkeys -K /tmp/pkg/signed_rpm.rpm
/tmp/pkg/signed_rpm.rpm: (md5) pgp OK
```

The `(md5) pgp OK` led me to try md5 which worked, I thus far have not been able to figure out why `-Kv` shows correctly and `-K` shows md5.

**Comment by djgilcrease** [comment] 2020-12-21 22:30
Ok figured it out, and it is confusing. Will have an rpmpack MR in a few

**Comment by caarlos0** [comment] 2020-12-22 11:23
Need to remove the replace once google/rpmpack#53 is merged... will leave this issue open until then :) 


Thanks @djgilcrease 🚀

**Closed** 2020-12-25 23:29 UTC
Labels: bug

**Comment by tentator** [comment] 2021-01-05 08:29
I also just wanted to mention that in general that generated package is strange and missing all manner of regular, important and even required tags. No released version of rpm produces packages like this.

For instance it's missing SHA1HEADER and SIGMD5 tags, the latter being required by LSB for example.
RHEL 7 rpm doesn't support the SHA256 digests that are present in the package, and while the signature that is there is technically supported, it's a header+payload signature which cannot be used during installation (rpmsign creates both a header-only and header+payload signatures), so there's no supported means to verify it!

So just FYI.

Cisco.

**Comment by erikgeiser** [comment] 2021-01-07 19:28
@tentator I would very much like to fix that, but we rely on https://github.com/google/rpmpack to handle that stuff. I also find it hard to find proper documentation for that kind of package format stuff. Could you maybe open an issue for https://github.com/google/rpmpack and leave some pointers on how we can find information about the requirements?

**Comment by tentator** [comment] 2021-01-11 14:09
Ah I understand now.. then it's because of the downsides of rpmpack!

It's mentioned as such:

    Is not related to the team the builds rpmlib.
    May easily wreak havoc on rpm based systems. It is surprisingly easy to cause rpm to segfault on corrupt rpm files.
    Many features are missing.
    All of the artifacts are stored in memory, sometimes more than once.
    Less backwards compatible than rpmbuild.

:)
