### ISSUE TITLE
Pre-release version of created RPM packages don't sort correctly

### ISSUE THREAD

**Issue by troian** [goreleaser/nfpm#54] opened 2019-05-25 20:37 UTC
**Describe the bug**

nfpm package [replaces](https://github.com/goreleaser/nfpm/blob/ce9ed27f160966c6ae7f31692784b3f7bff95755/rpm/rpm.go#L48) `-` to `_` which seems to break RPM version guidelines

https://www.thegeekdiary.com/understanding-rpm-versions-and-naming-schemes

**Reproduce**

Try create packages with versions `v1.1.1_beta1` and `v1.1.1_beta2`. Install `v1.1.1_beta1` followed by update to `v1.1.1_beta2` which is ignored

**Comment by caarlos0** [comment] 2019-05-25 21:13
I was looking into this... this is as intended, actually: https://github.com/goreleaser/nfpm/issues/24

it won't accept `1.2.3-beta1` as a version...

afaik there is no way to add a "prerelease" tag to the version to the rpm spec... but I'm not well versed in RPM so I may be wrong...

**Comment by troian** [comment] 2019-05-25 21:41
Found this sort of explanation https://serverfault.com/a/867567

**Comment by djgilcrease** [comment] 2019-10-03 22:52
This should be fixed by #79 so long as you use a version like `v1.2.3-0.1.beta`

**Closed** 2019-10-09 20:52 UTC
Labels: bug

**Comment by caarlos0** [comment] 2020-11-17 00:49
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
