### ISSUE TITLE
Empty directory are not copied

### ISSUE THREAD

**Issue by muthukrishnan24** [goreleaser/nfpm#511] opened 2022-05-23 14:47 UTC
### What happened?

Empty directories are not copied in deb packager

### How can we reproduce this?

contents:
  - src: path/to/local/dir
    dst: /usr/local/dir

Say empty directories inside dir/data/archive
Where archive/ dir is empty it is not packed into the deb

### nfpm version

```bash
v2.15.1
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment] 2022-05-23 14:49
that's expected, you can make empty dir in the the package with:

```yaml
  - dst: /usr/local/dir
    type: dir
```

**Comment by muthukrishnan24** [comment] 2022-05-23 14:52
Yes, I tried it and it works.
Problem is there are too many empty directories to create

**Comment by caarlos0** [comment] 2022-05-23 23:43
right now the only way is to either create the dir structure as my previous comment or to add some file to the folders you're trying to copy in order to make them not empty...

**Comment by caarlos0** [comment] 2022-05-30 12:28
working as intended, closing...

**Closed by caarlos0** 2022-05-30 12:28 UTC
Labels: bug
